name: flutter_listin
description: Listin - Feira Fácil!

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Nativo
  cupertino_icons: ^1.0.2

  # Outros pacotes
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: '^0.13.1'
  uuid: ^4.3.3
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.8.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.7.0
  logger: ^2.5.0
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5

  # Pacotes do curso

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  test: ^1.25.2
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - 'assets/'

flutter_native_splash:
  color: '#cce663'
  image: assets/logo.png
  android_12:
    color: '#cce663'
    icon_background_color: '#cce663'
    image: assets/logo_1152.png

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo.png'
  min_sdk_android: 21
